[package]
name = "binance-async-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
futures-util = "0.3.29"
hex = "0.4.3"
hmac = "0.12.1"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_qs = "0.12.0"
sha2 = "0.10.8"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tokio-tungstenite = "0.20.1"
url = "2.5.0"
